# generated by datamodel-codegen:
#   filename:  contracts.json

from __future__ import annotations

from datetime import date
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SourceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_digest: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    file_name: str
    sheet: str
    physical_row: Annotated[int, Field(ge=2)]


class SourceIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legal_entity: str
    vehicle: str
    batch_id: str
    je_index: str
    transaction_index: str
    rfx_id: str
    occurrence_index: Annotated[int, Field(ge=0)]


class MappingRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    table: Literal['LE', 'CoA', 'Investor', 'Deal', 'BatchPreference', 'CorvusCoA']
    source: SourceRef
    version: Annotated[int, Field(ge=1)]


class DecisionRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decision_id: str
    version: Annotated[int, Field(ge=1)]


class Money(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount: Annotated[str, Field(pattern='^-?[0-9]+(\\.[0-9]+)?$')]
    currency: Annotated[str, Field(pattern='^[A-Z]{3}$')]


class Destination(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legal_entity: str
    legal_entity_id: str
    gl_date: date
    effective_date: date
    deal_name: str | None = None
    deal_id: str | None = None
    position: str | None = None
    position_id: str | None = None
    trans_type: str
    transaction_currency: Annotated[str, Field(pattern='^[A-Z]{3}$')]
    investor_amount_local: Money
    is_debit: bool
    investor_amount_le: Money
    batch_type: str
    batch_comments: str | None = None
    transaction_comments: str | None = None
    allocation_rule: str
    investor_account_id: str
    vehicle: str
    bank_account: str | None = None
    udf_lookup: str | None = None
    udf_text: str | None = None
    supplier: str | None = None
    investor_quantity: str | None = None


class Warning(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    message: str
    refs: list[SourceRef] | None = None


class Gap(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_gl_account: str
    source_trans_type: str
    proposed_target: dict[str, Any] | None = None
    affected_source_refs: Annotated[list[SourceRef], Field(min_length=1)]


class Target(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gl_account: str
    trans_type: str
    corvus_ref: SourceRef


class Decision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decision_id: str
    version: Annotated[int, Field(ge=1)]
    gap: Gap
    target: Target
    author: str
    reason: Annotated[str, Field(min_length=1)]
    decided_at: AwareDatetime
    supersedes: int | None


class SourceRow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    values: dict[str, str]
    source: SourceRef


class Verified(
    RootModel[Literal['verified', 'partial', 'unverified', 'not_applicable']]
):
    root: Literal['verified', 'partial', 'unverified', 'not_applicable']


class Receipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    submission_id: str
    company: str
    state: Literal[
        'prepared',
        'draft_saved',
        'submitted',
        'verified',
        'rejected',
        'unknown',
        'drifted',
    ]
    doc_names: list[str]
    artifact_digest: str
    response_digest: str | None
    verified_at: str | None
    posted_at: str | None
    detail: str


class BatchKey(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legal_entity: str
    source_batch_id: str


class Posting(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract_version: Literal[1]
    posting_id: str
    batch_key: BatchKey
    source_refs: Annotated[list[SourceRef], Field(min_length=1)]
    source_identity: SourceIdentity
    mappings_used: list[MappingRef]
    decisions_used: list[DecisionRef]
    status: Literal['ready', 'needs_decision', 'blocked', 'stale']
    block_reason: str | None = None
    destination: Destination | None
    warnings: list[Warning]


class Release(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    release_id: str
    batch_key: BatchKey
    state: Literal['draft', 'approved', 'stale', 'revoked']
    bound_decisions: list[DecisionRef]
    mapping_snapshot_digest: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    posting_ids: list[str]
    approved_by: str | None
    approved_at: AwareDatetime | None
    state_changed_at: AwareDatetime
    state_reason: str


class Export(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    export_id: str
    created_at: AwareDatetime
    scope: Literal['approved_only', 'review_draft']
    batch_keys: list[BatchKey]
    release_states_at_export: dict[str, str]
    file_digest: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    label: Literal['Exported; destination not checked']


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_evidence: Verified
    investor_allocation: Verified
    decision_author_reason: Verified
    destination_receipt: Verified
    change_impact: Verified


class Contracts(BaseModel):
    SourceRef_1: Annotated[SourceRef | None, Field(alias='SourceRef')] = None
    SourceIdentity_1: Annotated[
        SourceIdentity | None, Field(alias='SourceIdentity')
    ] = None
    MappingRef_1: Annotated[MappingRef | None, Field(alias='MappingRef')] = None
    DecisionRef_1: Annotated[DecisionRef | None, Field(alias='DecisionRef')] = None
    Money_1: Annotated[Money | None, Field(alias='Money')] = None
    Destination_1: Annotated[Destination | None, Field(alias='Destination')] = None
    Warning_1: Annotated[Warning | None, Field(alias='Warning')] = None
    Decision_1: Annotated[Decision | None, Field(alias='Decision')] = None
    Release_1: Annotated[Release | None, Field(alias='Release')] = None
    Export_1: Annotated[Export | None, Field(alias='Export')] = None
    SourceRow_1: Annotated[SourceRow | None, Field(alias='SourceRow')] = None
    Capabilities_1: Annotated[Capabilities | None, Field(alias='Capabilities')] = None
    Verified_1: Annotated[Verified | None, Field(alias='Verified')] = None
    Receipt_1: Annotated[Receipt | None, Field(alias='Receipt')] = None
    Posting_1: Annotated[Posting | None, Field(alias='Posting')] = None
    BatchKey_1: Annotated[BatchKey | None, Field(alias='BatchKey')] = None
