// Generated from contracts/*.json.
export type SourceRef = { "file_digest": string; "file_name": string; "sheet": string; "physical_row": number };
export type SourceIdentity = { "legal_entity": string; "vehicle": string; "batch_id": string; "je_index": string; "transaction_index": string; "rfx_id": string; "occurrence_index": number };
export type MappingRef = { "table": "LE" | "CoA" | "Investor" | "Deal" | "BatchPreference" | "CorvusCoA"; "source": SourceRef; "version": number };
export type DecisionRef = { "decision_id": string; "version": number };
export type Money = { "amount": string; "currency": string };
export type Destination = { "legal_entity": string; "legal_entity_id": string; "gl_date": string; "effective_date": string; "deal_name"?: string | null; "deal_id"?: string | null; "position"?: string | null; "position_id"?: string | null; "trans_type": string; "transaction_currency": string; "investor_amount_local": Money; "is_debit": boolean; "investor_amount_le": Money; "batch_type": string; "batch_comments"?: string | null; "transaction_comments"?: string | null; "allocation_rule": string; "investor_account_id": string; "vehicle": string; "bank_account"?: string | null; "udf_lookup"?: string | null; "udf_text"?: string | null; "supplier"?: string | null; "investor_quantity"?: string | null };
export type Warning = { "code": string; "message": string; "refs"?: Array<SourceRef> };
export type Decision = { "decision_id": string; "version": number; "gap": { "source_gl_account": string; "source_trans_type": string; "proposed_target"?: Record<string, unknown> | null; "affected_source_refs": Array<SourceRef> }; "target": { "gl_account": string; "trans_type": string; "corvus_ref": SourceRef }; "author": string; "reason": string; "decided_at": string; "supersedes": number | null };
export type Release = { "release_id": string; "batch_key": BatchKey; "state": "draft" | "approved" | "stale" | "revoked"; "bound_decisions": Array<DecisionRef>; "mapping_snapshot_digest": string; "posting_ids": Array<string>; "approved_by": string | null; "approved_at": string | null; "state_changed_at": string; "state_reason": string };
export type Export = { "export_id": string; "created_at": string; "scope": "approved_only" | "review_draft"; "batch_keys": Array<BatchKey>; "release_states_at_export": Record<string, string>; "file_digest": string; "label": "Exported; destination not checked" };
export type SourceRow = { "values": Record<string, string>; "source": SourceRef };
export type Capabilities = { "source_evidence": Verified; "investor_allocation": Verified; "decision_author_reason": Verified; "destination_receipt": Verified; "change_impact": Verified };
export type Verified = "verified" | "partial" | "unverified" | "not_applicable";
export type Receipt = { "submission_id": string; "company": string; "state": "prepared" | "draft_saved" | "submitted" | "verified" | "rejected" | "unknown" | "drifted"; "doc_names": Array<string>; "artifact_digest": string; "response_digest": string | null; "verified_at": string | null; "posted_at": string | null; "detail": string };
export type Posting = { "contract_version": 1; "posting_id": string; "batch_key": { "legal_entity": string; "source_batch_id": string }; "source_refs": Array<SourceRef>; "source_identity": SourceIdentity; "mappings_used": Array<MappingRef>; "decisions_used": Array<DecisionRef>; "status": "ready" | "needs_decision" | "blocked" | "stale"; "block_reason"?: string | null; "destination": Destination | null; "warnings": Array<Warning> };
export type BatchKey = { "legal_entity": string; "source_batch_id": string };
